In [1]:
import xarray
import numpy as np
import pandas as pd

In [2]:
ds = xarray.open_dataset("dataset/source-era5_date-2022-01-01_res-0.25_levels-13_steps-12.nc")

In [3]:
ds

<xarray.Dataset> Size: 5GB
Dimensions:                       (lon: 1440, lat: 721, time: 14, level: 13,
                                   batch: 1)
Coordinates:
  * lon                           (lon) float32 6kB 0.0 0.25 0.5 ... 359.5 359.8
  * lat                           (lat) float32 3kB -90.0 -89.75 ... 89.75 90.0
  * time                          (time) timedelta64[ns] 112B 0 days 00:00:00...
  * level                         (level) int32 52B 50 100 150 ... 850 925 1000
    datetime                      (batch, time) datetime64[ns] 112B ...
Dimensions without coordinates: batch
Data variables: (12/14)
    geopotential_at_surface       (lat, lon) float32 4MB ...
    land_sea_mask                 (lat, lon) float32 4MB ...
    2m_temperature                (batch, time, lat, lon) float32 58MB ...
    mean_sea_level_pressure       (batch, time, lat, lon) float32 58MB ...
    10m_v_component_of_wind       (batch, time, lat, lon) float32 58MB ...
    10m_u_component_of_wind       (batch, time, lat, lon) float32 58MB ...
    ...                            ...
    temperature                   (batch, time, level, lat, lon) float32 756MB ...
    geopotential                  (batch, time, level, lat, lon) float32 756MB ...
    u_component_of_wind           (batch, time, level, lat, lon) float32 756MB ...
    v_component_of_wind           (batch, time, level, lat, lon) float32 756MB ...
    vertical_velocity             (batch, time, level, lat, lon) float32 756MB ...
    specific_humidity             (batch, time, level, lat, lon) float32 756MB ...

In [4]:
ds['datetime'].values

array([['2022-01-01T00:00:00.000000000', '2022-01-01T06:00:00.000000000',
        '2022-01-01T12:00:00.000000000', '2022-01-01T18:00:00.000000000',
        '2022-01-02T00:00:00.000000000', '2022-01-02T06:00:00.000000000',
        '2022-01-02T12:00:00.000000000', '2022-01-02T18:00:00.000000000',
        '2022-01-03T00:00:00.000000000', '2022-01-03T06:00:00.000000000',
        '2022-01-03T12:00:00.000000000', '2022-01-03T18:00:00.000000000',
        '2022-01-04T00:00:00.000000000', '2022-01-04T06:00:00.000000000']],
      dtype='datetime64[ns]')

In [5]:
ds['2m_temperature']

<xarray.DataArray '2m_temperature' (batch: 1, time: 14, lat: 721, lon: 1440)> Size: 58MB
[14535360 values with dtype=float32]
Coordinates:
  * lon       (lon) float32 6kB 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * lat       (lat) float32 3kB -90.0 -89.75 -89.5 -89.25 ... 89.5 89.75 90.0
  * time      (time) timedelta64[ns] 112B 0 days 00:00:00 ... 3 days 06:00:00
    datetime  (batch, time) datetime64[ns] 112B 2022-01-01 ... 2022-01-04T06:...
Dimensions without coordinates: batch

In [6]:
ds['temperature']

<xarray.DataArray 'temperature' (batch: 1, time: 14, level: 13, lat: 721,
                                 lon: 1440)> Size: 756MB
[188959680 values with dtype=float32]
Coordinates:
  * lon       (lon) float32 6kB 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * lat       (lat) float32 3kB -90.0 -89.75 -89.5 -89.25 ... 89.5 89.75 90.0
  * time      (time) timedelta64[ns] 112B 0 days 00:00:00 ... 3 days 06:00:00
  * level     (level) int32 52B 50 100 150 200 250 300 ... 600 700 850 925 1000
    datetime  (batch, time) datetime64[ns] 112B 2022-01-01 ... 2022-01-04T06:...
Dimensions without coordinates: batch

In [7]:
ds['geopotential_at_surface'].values

array([[ 2.7354750e+04,  2.7354750e+04,  2.7354750e+04, ...,
         2.7354750e+04,  2.7354750e+04,  2.7354750e+04],
       [ 2.7163490e+04,  2.7165285e+04,  2.7167082e+04, ...,
         2.7159000e+04,  2.7159898e+04,  2.7161693e+04],
       [ 2.6957861e+04,  2.6961453e+04,  2.6965045e+04, ...,
         2.6949779e+04,  2.6952475e+04,  2.6956066e+04],
       ...,
       [-1.8730469e+00, -1.8730469e+00, -1.8730469e+00, ...,
        -1.8730469e+00, -1.8730469e+00, -1.8730469e+00],
       [ 4.4121094e+00,  4.4121094e+00,  4.4121094e+00, ...,
         4.4121094e+00,  4.4121094e+00,  4.4121094e+00],
       [-7.6171875e-02, -7.6171875e-02, -7.6171875e-02, ...,
        -7.6171875e-02, -7.6171875e-02, -7.6171875e-02]], dtype=float32)

In [8]:
ds['land_sea_mask']

<xarray.DataArray 'land_sea_mask' (lat: 721, lon: 1440)> Size: 4MB
[1038240 values with dtype=float32]
Coordinates:
  * lon      (lon) float32 6kB 0.0 0.25 0.5 0.75 1.0 ... 359.0 359.2 359.5 359.8
  * lat      (lat) float32 3kB -90.0 -89.75 -89.5 -89.25 ... 89.5 89.75 90.0

In [9]:
ds['land_sea_mask'].values.shape

(721, 1440)

In [10]:
ds['land_sea_mask'].values.sum()

348741.97

In [11]:
np.savetxt('z.csv', ds['geopotential_at_surface'].values, delimiter=',')
np.savetxt('lsm.csv', ds['land_sea_mask'].values, delimiter=',')

In [12]:
ds['geopotential_at_surface'].to_netcdf('geopotential_at_surface-0.25.nc')
ds['land_sea_mask'].to_netcdf('land_sea_mask-0.25.nc')

In [13]:
z = xarray.open_dataset('geopotential_at_surface-0.25.nc')

In [14]:
z

<xarray.Dataset> Size: 4MB
Dimensions:                  (lon: 1440, lat: 721)
Coordinates:
  * lon                      (lon) float32 6kB 0.0 0.25 0.5 ... 359.5 359.8
  * lat                      (lat) float32 3kB -90.0 -89.75 -89.5 ... 89.75 90.0
Data variables:
    geopotential_at_surface  (lat, lon) float32 4MB ...

In [15]:
ds2 = xarray.open_dataset("dataset/source-hres_date-2022-01-01_res-0.25_levels-13_steps-01.nc")

In [16]:
ds2

<xarray.Dataset> Size: 1GB
Dimensions:                       (lon: 1440, lat: 721, level: 13, time: 3,
                                   batch: 1)
Coordinates:
  * lon                           (lon) float32 6kB 0.0 0.25 0.5 ... 359.5 359.8
  * lat                           (lat) float32 3kB -90.0 -89.75 ... 89.75 90.0
  * level                         (level) int32 52B 50 100 150 ... 850 925 1000
  * time                          (time) timedelta64[ns] 24B 00:00:00 ... 12:...
    datetime                      (batch, time) datetime64[ns] 24B ...
Dimensions without coordinates: batch
Data variables: (12/14)
    geopotential_at_surface       (lat, lon) float32 4MB ...
    land_sea_mask                 (lat, lon) float32 4MB ...
    2m_temperature                (batch, time, lat, lon) float32 12MB ...
    mean_sea_level_pressure       (batch, time, lat, lon) float32 12MB ...
    10m_v_component_of_wind       (batch, time, lat, lon) float32 12MB ...
    10m_u_component_of_wind       (batch, time, lat, lon) float32 12MB ...
    ...                            ...
    temperature                   (batch, time, level, lat, lon) float32 162MB ...
    geopotential                  (batch, time, level, lat, lon) float32 162MB ...
    u_component_of_wind           (batch, time, level, lat, lon) float32 162MB ...
    v_component_of_wind           (batch, time, level, lat, lon) float32 162MB ...
    vertical_velocity             (batch, time, level, lat, lon) float32 162MB ...
    specific_humidity             (batch, time, level, lat, lon) float32 162MB ...

In [17]:
ds2['datetime'].values

array([['2022-01-01T00:00:00.000000000', '2022-01-01T06:00:00.000000000',
        '2022-01-01T12:00:00.000000000']], dtype='datetime64[ns]')

In [18]:
ds2['geopotential_at_surface'].values

array([[ 2.7354750e+04,  2.7354750e+04,  2.7354750e+04, ...,
         2.7354750e+04,  2.7354750e+04,  2.7354750e+04],
       [ 2.7163490e+04,  2.7165285e+04,  2.7167082e+04, ...,
         2.7159000e+04,  2.7159898e+04,  2.7161693e+04],
       [ 2.6957861e+04,  2.6961453e+04,  2.6965045e+04, ...,
         2.6949779e+04,  2.6952475e+04,  2.6956066e+04],
       ...,
       [-1.8730469e+00, -1.8730469e+00, -1.8730469e+00, ...,
        -1.8730469e+00, -1.8730469e+00, -1.8730469e+00],
       [ 4.4121094e+00,  4.4121094e+00,  4.4121094e+00, ...,
         4.4121094e+00,  4.4121094e+00,  4.4121094e+00],
       [-7.6171875e-02, -7.6171875e-02, -7.6171875e-02, ...,
        -7.6171875e-02, -7.6171875e-02, -7.6171875e-02]], dtype=float32)

In [19]:
ds2['land_sea_mask'].values

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [20]:
np.savetxt('z2.csv', ds2['geopotential_at_surface'].values, delimiter=',')
np.savetxt('lsm2.csv', ds2['land_sea_mask'].values, delimiter=',')

In [21]:
u10_ds = xarray.open_dataset(f'/fsx/datalab/nsf-ncar-era5/e5.oper.an.sfc/202301/e5.oper.an.sfc.128_165_10u.ll025sc.2023010100_2023013123.nc')


In [22]:
u10_ds

<xarray.Dataset> Size: 3GB
Dimensions:    (time: 744, latitude: 721, longitude: 1440)
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 6kB 2023-01-01 ... 2023-01-31T23:00:00
Data variables:
    VAR_10U    (time, latitude, longitude) float32 3GB ...
    utc_date   (time) int32 3kB ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r1i2n21 4.12.14-95.51-default #1 SMP Fri Apr ...
    CONVERSION_DATE:      Sat Apr 15 16:10:18 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Sat Apr 15 16:10:34 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [23]:
u_ds = xarray.open_dataset(f'/fsx/datalab/nsf-ncar-era5/e5.oper.an.pl/202301/e5.oper.an.pl.128_131_u.ll025uv.2023010100_2023010123.nc')


In [24]:
u_ds

<xarray.Dataset> Size: 4GB
Dimensions:    (time: 24, level: 37, latitude: 721, longitude: 1440)
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * level      (level) float64 296B 1.0 2.0 3.0 5.0 ... 925.0 950.0 975.0 1e+03
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 192B 2023-01-01 ... 2023-01-01T23:00:00
Data variables:
    U          (time, level, latitude, longitude) float32 4GB ...
    utc_date   (time) int32 96B ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB 1 data to netC...
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r1i4n11 4.12.14-95.51-default #1 SMP Fri Apr ...
    CONVERSION_DATE:      Sat Apr 15 15:14:44 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Sat Apr 15 15:15:01 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [25]:
mtpr_ds1 = xarray.open_dataset(f'/fsx/datalab/nsf-ncar-era5/e5.oper.fc.sfc.meanflux/202301/e5.oper.fc.sfc.meanflux.235_055_mtpr.ll025sc.2023010106_2023011606.nc')
mtpr_ds2 = xarray.open_dataset(f'/fsx/datalab/nsf-ncar-era5/e5.oper.fc.sfc.meanflux/202301/e5.oper.fc.sfc.meanflux.235_055_mtpr.ll025sc.2023011606_2023020106.nc')
mtpr_ds = xarray.merge([mtpr_ds1, mtpr_ds2])

In [26]:
mtpr_ds

<xarray.Dataset> Size: 3GB
Dimensions:                (forecast_hour: 12, forecast_initial_time: 62,
                            latitude: 721, longitude: 1440)
Coordinates:
  * forecast_hour          (forecast_hour) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * forecast_initial_time  (forecast_initial_time) datetime64[ns] 496B 2023-0...
  * latitude               (latitude) float64 6kB 90.0 89.75 ... -89.75 -90.0
  * longitude              (longitude) float64 12kB 0.0 0.25 0.5 ... 359.5 359.8
Data variables:
    MTPR                   (forecast_initial_time, forecast_hour, latitude, longitude) float32 3GB ...
    utc_date               (forecast_initial_time) float64 496B 2.023e+09 ......
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r12i6n23 4.12.14-95.51-default #1 SMP Fri Apr...
    CONVERSION_DATE:      Tue May  2 10:46:16 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Tue May  2 10:46:24 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [27]:
def create_actual_time(ds):
    # 创建网格化的时间
    init_times = ds.forecast_initial_time.values[:, np.newaxis]  # 添加一个维度以便广播
    forecast_hours = pd.Timedelta(hours=1) * (ds.forecast_hour.values-1)  # 转换小时为时间差
    
    # 广播并相加得到实际时间
    actual_times = init_times + forecast_hours
    
    # 重塑数据，将forecast_initial_time和forecast_hour合并为单个time维度
    ds_new = ds.stack(time=('forecast_initial_time', 'forecast_hour'))
    
    # 将计算出的实际时间赋值给新维度
    ds_new.coords['time'] = actual_times.ravel()
    
    # # 删除原始的forecast维度
    # ds_new = ds_new.drop(['forecast_initial_time', 'forecast_hour'])
    
    # 调整维度顺序为 (time, latitude, longitude)
    ds_new = ds_new.transpose('time', 'latitude', 'longitude')
    
    return ds_new

In [28]:
mtpr_ds_new = create_actual_time(mtpr_ds)

/tmp/ipykernel_104072/3428041751.py:13: FutureWarning: updating coordinate 'time' with a PandasMultiIndex would leave the multi-index level coordinates ['forecast_initial_time', 'forecast_hour'] in an inconsistent state. This will raise an error in the future. Use `.drop_vars(['time', 'forecast_initial_time', 'forecast_hour'])` before assigning new coordinate values.
  ds_new.coords['time'] = actual_times.ravel()


In [29]:
mtpr_ds_new

<xarray.Dataset> Size: 3GB
Dimensions:    (latitude: 721, longitude: 1440, time: 744)
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 6kB 2023-01-01T06:00:00 ... 2023-02-01T0...
Data variables:
    MTPR       (time, latitude, longitude) float32 3GB 2.384e-07 ... 2.742e-06
    utc_date   (time) float64 6kB 2.023e+09 2.023e+09 ... 2.023e+09 2.023e+09
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r12i6n23 4.12.14-95.51-default #1 SMP Fri Apr...
    CONVERSION_DATE:      Tue May  2 10:46:16 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Tue May  2 10:46:24 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [30]:
tisr_ds = xarray.open_dataset(f'/fsx/datalab/nsf-ncar-era5/e5.oper.fc.sfc.accumu/202301/e5.oper.fc.sfc.accumu.128_212_tisr.ll025sc.2023011606_2023020106.nc')


In [31]:
tisr_ds

<xarray.Dataset> Size: 2GB
Dimensions:                (forecast_initial_time: 32, forecast_hour: 12,
                            latitude: 721, longitude: 1440)
Coordinates:
  * forecast_hour          (forecast_hour) int32 48B 1 2 3 4 5 6 7 8 9 10 11 12
  * forecast_initial_time  (forecast_initial_time) datetime64[ns] 256B 2023-0...
  * latitude               (latitude) float64 6kB 90.0 89.75 ... -89.75 -90.0
  * longitude              (longitude) float64 12kB 0.0 0.25 0.5 ... 359.5 359.8
Data variables:
    TISR                   (forecast_initial_time, forecast_hour, latitude, longitude) float32 2GB ...
    utc_date               (forecast_initial_time) int32 128B ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r4i3n19 4.12.14-95.51-default #1 SMP Fri Apr ...
    CONVERSION_DATE:      Tue May  2 11:16:03 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Tue May  2 11:16:12 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [32]:
tisr_ds_new = create_actual_time(tisr_ds)

/tmp/ipykernel_104072/3428041751.py:13: FutureWarning: updating coordinate 'time' with a PandasMultiIndex would leave the multi-index level coordinates ['forecast_initial_time', 'forecast_hour'] in an inconsistent state. This will raise an error in the future. Use `.drop_vars(['time', 'forecast_initial_time', 'forecast_hour'])` before assigning new coordinate values.
  ds_new.coords['time'] = actual_times.ravel()


In [33]:
tisr_ds_new

<xarray.Dataset> Size: 2GB
Dimensions:    (latitude: 721, longitude: 1440, time: 384)
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 3kB 2023-01-16T06:00:00 ... 2023-02-01T0...
Data variables:
    TISR       (time, latitude, longitude) float32 2GB 0.0 0.0 ... 1.505e+06
    utc_date   (time) int32 2kB 2023011606 2023011606 ... 2023013118 2023013118
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r4i3n19 4.12.14-95.51-default #1 SMP Fri Apr ...
    CONVERSION_DATE:      Tue May  2 11:16:03 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Tue May  2 11:16:12 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [34]:
z_ds = xarray.open_dataset(f'/fsx/datalab/nsf-ncar-era5/e5.oper.invariant/197901/e5.oper.invariant.128_129_z.ll025sc.1979010100_1979010100.nc')


In [35]:
z_ds

<xarray.Dataset> Size: 4MB
Dimensions:    (time: 1, latitude: 721, longitude: 1440)
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 8B 1979-01-01
Data variables:
    Z          (time, latitude, longitude) float32 4MB ...
    utc_date   (time) int32 4B ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.6.1
    CONVERSION_PLATFORM:  Linux casper04 3.10.0-693.21.1.el7.x86_64 #1 SMP We...
    CONVERSION_DATE:      Mon May 13 18:10:32 MDT 2019
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Mon May 13 18:10:32 2019: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 4.7.4 (http://nco.sf.net)

In [36]:
z_ds['Z'].values

array([[[ 3.2275391e-01,  3.2275391e-01,  3.2275391e-01, ...,
          3.2275391e-01,  3.2275391e-01,  3.2275391e-01],
        [ 4.6157227e+00,  4.6040039e+00,  4.5883789e+00, ...,
          4.7915039e+00,  4.7329102e+00,  4.6743164e+00],
        [-1.7709961e+00, -1.7163086e+00, -1.7084961e+00, ...,
         -1.5092773e+00, -1.6225586e+00, -1.7124023e+00],
        ...,
        [ 2.6958170e+04,  2.6961174e+04,  2.6964666e+04, ...,
          2.6949771e+04,  2.6952857e+04,  2.6955689e+04],
        [ 2.7163209e+04,  2.7165209e+04,  2.7167213e+04, ...,
          2.7158693e+04,  2.7160193e+04,  2.7161701e+04],
        [ 2.7355104e+04,  2.7355104e+04,  2.7355104e+04, ...,
          2.7355104e+04,  2.7355104e+04,  2.7355104e+04]]], dtype=float32)

In [37]:
flipped_z = np.flip(z_ds['Z'].values[0], axis=0)

In [38]:
flipped_z

array([[ 2.7355104e+04,  2.7355104e+04,  2.7355104e+04, ...,
         2.7355104e+04,  2.7355104e+04,  2.7355104e+04],
       [ 2.7163209e+04,  2.7165209e+04,  2.7167213e+04, ...,
         2.7158693e+04,  2.7160193e+04,  2.7161701e+04],
       [ 2.6958170e+04,  2.6961174e+04,  2.6964666e+04, ...,
         2.6949771e+04,  2.6952857e+04,  2.6955689e+04],
       ...,
       [-1.7709961e+00, -1.7163086e+00, -1.7084961e+00, ...,
        -1.5092773e+00, -1.6225586e+00, -1.7124023e+00],
       [ 4.6157227e+00,  4.6040039e+00,  4.5883789e+00, ...,
         4.7915039e+00,  4.7329102e+00,  4.6743164e+00],
       [ 3.2275391e-01,  3.2275391e-01,  3.2275391e-01, ...,
         3.2275391e-01,  3.2275391e-01,  3.2275391e-01]], dtype=float32)

In [39]:
np.savetxt('flipped_z.csv', flipped_z, delimiter=',')

In [40]:
lsm_ds = xarray.open_dataset('/fsx/datalab/nsf-ncar-era5/e5.oper.invariant/197901/e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc')

In [41]:
lsm_ds

<xarray.Dataset> Size: 4MB
Dimensions:    (time: 1, latitude: 721, longitude: 1440)
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 8B 1979-01-01
Data variables:
    LSM        (time, latitude, longitude) float32 4MB ...
    utc_date   (time) int32 4B ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.6.1
    CONVERSION_PLATFORM:  Linux casper04 3.10.0-693.21.1.el7.x86_64 #1 SMP We...
    CONVERSION_DATE:      Mon May 13 18:10:35 MDT 2019
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Mon May 13 18:10:35 2019: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 4.7.4 (http://nco.sf.net)

In [42]:
lsm_ds['LSM']

<xarray.DataArray 'LSM' (time: 1, latitude: 721, longitude: 1440)> Size: 4MB
[1038240 values with dtype=float32]
Coordinates:
  * latitude   (latitude) float64 6kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float64 12kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 8B 1979-01-01
Attributes: (12/14)
    long_name:                     Land-sea mask
    short_name:                    lsm
    units:                         (0-1)
    original_format:               WMO GRIB 1 with ECMWF local table
    ecmwf_local_table:             128
    ecmwf_parameter:               172
    ...                            ...
    grid_specification:            0.25 degree x 0.25 degree from 90N to 90S ...
    rda_dataset:                   ds633.0
    rda_dataset_url:               https:/rda.ucar.edu/datasets/ds633.0/
    rda_dataset_doi:               DOI: 10.5065/BH6N-5N20
    rda_dataset_group:             ERA5 atmospheric invariant fields [netCDF4]
    number_of_significant_digits:  7

In [43]:
lsm_ds['LSM'].values.shape

(1, 721, 1440)

In [44]:
lsm_ds['LSM'].sum()

<xarray.DataArray 'LSM' ()> Size: 4B
array(348742.03, dtype=float32)

In [45]:
lsm_ds['LSM'].values[0].shape

(721, 1440)

In [46]:
flipped_lsm = np.flip(lsm_ds['LSM'].values[0], axis=0)

In [47]:
flipped_lsm

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [48]:
np.savetxt('flipped_lsm.csv', flipped_lsm, delimiter=',')

In [49]:
upper_ds = xarray.open_dataset('/fsx/datalab/nsf-ncar-era5/upper/upper_2023010100.nc')

In [50]:
upper_ds

<xarray.Dataset> Size: 324MB
Dimensions:              (level: 13, latitude: 721, longitude: 1440)
Coordinates:
  * latitude             (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * level                (level) float64 104B 1e+03 925.0 850.0 ... 100.0 50.0
  * longitude            (longitude) float64 12kB 0.0 0.25 0.5 ... 359.5 359.8
    time                 datetime64[ns] 8B ...
Data variables:
    geopotential         (level, latitude, longitude) float32 54MB ...
    utc_date             int32 4B ...
    specific_humidity    (level, latitude, longitude) float32 54MB ...
    temperature          (level, latitude, longitude) float32 54MB ...
    u_component_of_wind  (level, latitude, longitude) float32 54MB ...
    v_component_of_wind  (level, latitude, longitude) float32 54MB ...
    vertical_velocity    (level, latitude, longitude) float32 54MB ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB 1 data to netC...
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r1i4n11 4.12.14-95.51-default #1 SMP Fri Apr ...
    CONVERSION_DATE:      Sat Apr 15 14:54:36 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Sat Apr 15 14:54:53 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...

In [51]:
surface_ds = xarray.open_dataset('/fsx/datalab/nsf-ncar-era5/surface/surface_2023010100.nc')

In [52]:
surface_ds

<xarray.Dataset> Size: 25MB
Dimensions:                       (latitude: 721, longitude: 1440)
Coordinates:
  * latitude                      (latitude) float64 6kB 90.0 89.75 ... -90.0
  * longitude                     (longitude) float64 12kB 0.0 0.25 ... 359.8
    time                          datetime64[ns] 8B ...
Data variables:
    mean_sea_level_pressure       (latitude, longitude) float32 4MB ...
    utc_date                      int32 4B ...
    10m_u_component_of_wind       (latitude, longitude) float32 4MB ...
    10m_v_component_of_wind       (latitude, longitude) float32 4MB ...
    2m_temperature                (latitude, longitude) float32 4MB ...
    total_precipitation_6hr       (latitude, longitude) float32 4MB ...
    toa_incident_solar_radiation  (latitude, longitude) float32 4MB ...
Attributes:
    DATA_SOURCE:          ECMWF: https://cds.climate.copernicus.eu, Copernicu...
    NETCDF_CONVERSION:    CISL RDA: Conversion from ECMWF GRIB1 data to netCDF4.
    NETCDF_VERSION:       4.8.1
    CONVERSION_PLATFORM:  Linux r1i2n21 4.12.14-95.51-default #1 SMP Fri Apr ...
    CONVERSION_DATE:      Sat Apr 15 16:01:46 MDT 2023
    Conventions:          CF-1.6
    NETCDF_COMPRESSION:   NCO: Precision-preserving compression to netCDF4/HD...
    history:              Sat Apr 15 16:02:01 2023: ncks -4 --ppc default=7 e...
    NCO:                  netCDF Operators version 5.0.3 (Homepage = http://n...